const operators = {
  "2:1": "Smoke",
  "3:1": "Mute",
  "4:1": "Sledge",
  "5:1": "Thatcher",
  "2:2": "Castle",
  "3:2": "Ash",
  "4:2": "Pulse",
  "5:2": "Thermite",
  "2:3": "Doc",
  "3:3": "Rook",
  "4:3": "Twitch",
  "5:3": "Montagne",
  "2:4": "Glaz",
  "3:4": "Fuze",
  "4:4": "Kapkan",
  "5:4": "Tachanka",
  "2:5": "Blitz",
  "3:5": "IQ",
  "4:5": "Jager",
  "5:5": "Bandit",
  "2:6": "Buck",
  "3:6": "Frost",
  "2:7": "Blackbeard",
  "3:7": "Valkyrie",
  "2:8": "Capitao",
  "3:8": "Caveira",
  "2:9": "Hibana",
  "3:9": "Echo",
  "2:A": "Jackal",
  "3:A": "Mira",
  "2:B": "Ying",
  "3:B": "Lesion",
  "2:C": "Ela",
  "3:C": "Zofia",
  "2:D": "Dokkaebi",
  "3:D": "Vigil",
  "3:E": "Lion",
  "4:E": "Finka",
  "2:F": "Maestro",
  "3:F": "Alibi",
  "2:10": "Maverick",
  "3:10": "Clash",
  "2:11": "Nomad",
  "3:11": "Kaid",
  "2:12": "Gridlock",
  "3:12": "Mozzie"
};

const getOperator = id => {
  return operators[id];
};

export default getOperator;
